### ISSUE TITLE
Page display problem

### ISSUE THREAD

**Issue by ArianeFire** [tibarix/egicom#1]
Please Guy have a look at your master file and optimize css, js... file loading.

**I RECOMMEND TO USE : ** something like : 
`<link rel="stylesheet" href="{{URL::asset("css/bootstrap.css")}}" />`

See Image below and the link to the app is also at the bottom.

![bug](https://cloud.githubusercontent.com/assets/12550052/21755085/32fe9ebc-d605-11e6-8926-c7001c1e3762.png)

[http://163.172.174.219/egicom/public/](url)

Thank for correcting it.

**Comment by medmek** [comment]
still having this issue ? despite having thous (failed to load) files in place ?
since this error involves different files the fix wouldn't be just to change the css source,
I feel like it has to do with routes ...

**Comment by tibarix** [comment]
guys I just pushed, and I believe I fixed the problem
